---
version: '3'
services:
  test-kafka:
    image: confluentinc/cp-kafka
    container_name: test-bamboo-kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: test-zookeeper:32182
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29093,INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://test-kafka:9092,EXTERNAL_SAME_HOST://localhost:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 29093:29092
    depends_on:
      - test-zookeeper
  test-zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: test-bamboo-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 32182
  test-redis:
    image: "redis:7.0"
    container_name: test-bamboo-redis
    ports:
      - "6380:6379"
