// Code generated by mockery v2.34.2. DO NOT EDIT.

package bamboo

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CloseSubscribeConnectionFunc is an autogenerated mock type for the CloseSubscribeConnectionFunc type
type CloseSubscribeConnectionFunc struct {
	mock.Mock
}

type CloseSubscribeConnectionFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *CloseSubscribeConnectionFunc) EXPECT() *CloseSubscribeConnectionFunc_Expecter {
	return &CloseSubscribeConnectionFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx
func (_m *CloseSubscribeConnectionFunc) Execute(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CloseSubscribeConnectionFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type CloseSubscribeConnectionFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
func (_e *CloseSubscribeConnectionFunc_Expecter) Execute(ctx interface{}) *CloseSubscribeConnectionFunc_Execute_Call {
	return &CloseSubscribeConnectionFunc_Execute_Call{Call: _e.mock.On("Execute", ctx)}
}

func (_c *CloseSubscribeConnectionFunc_Execute_Call) Run(run func(ctx context.Context)) *CloseSubscribeConnectionFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *CloseSubscribeConnectionFunc_Execute_Call) Return(_a0 error) *CloseSubscribeConnectionFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CloseSubscribeConnectionFunc_Execute_Call) RunAndReturn(run func(context.Context) error) *CloseSubscribeConnectionFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewCloseSubscribeConnectionFunc creates a new instance of CloseSubscribeConnectionFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCloseSubscribeConnectionFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *CloseSubscribeConnectionFunc {
	mock := &CloseSubscribeConnectionFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
